"""Engineering Knowledge Reconstruction and Intelligence."""

from .adaptive_exploration import (
    AdaptiveExplorationError,
    CompetencyQuestion,
    MissionBudget,
    assess_knowledge_sufficiency,
    build_candidate_knowledge_delta,
    build_mission_context,
    build_mission_exploration_plan,
    collect_git_path_evidence,
    evaluate_candidate_authority_route,
    initialize_wae_trace,
    record_wae_iteration,
)
from .core_boundary_reconstruction import (
    CoreBoundaryError,
    run_core_boundary_reconstruction,
)
from .core_extraction import (
    CoreExtractionError,
    run_core_extraction_audit,
)
from .core_migration import (
    CoreMigrationError,
    run_core_migration_audit,
)
from .capability_query import (
    CapabilityQueryError,
    CapabilityQueryService,
    evaluate_capability_before_generate,
    explain_authority,
    find_capability,
    get_evidence,
    get_realizations,
)
from .capability_contract import (
    CapabilityCheckRequest,
    ExistingCapabilityError,
    build_request,
)
from .existing_capability_intelligence import run_existing_capability_check
from .flow_query import (
    FlowQueryError,
    FlowQueryService,
    trace_flow,
)
from .evolution_intelligence import (
    ChangeImpactRequest,
    ChangeRegistration,
    EvolutionIntelligenceError,
    build_change_impact_request,
    build_change_registration,
    deferred_verification_needed,
    register_change,
    run_phase3_evolution_analysis,
    transition_change_registration,
)
from .git_evidence import AdmittedEvidenceError, AdmittedGitReader, BlobReceipt
from .minimal_core_contract import (
    MinimalCoreContractError,
    run_minimal_core_contract,
)
from .knowledge_reconstruction import (
    EVIDENCE_SCHEMA_VERSION,
    MEMORY_SCHEMA_VERSION,
    PROFILE_ID,
    REPORT_SCHEMA_VERSION,
    KnowledgeReconstructionError,
    build_wff_architecture_memory,
    load_fixed_observation_manifest,
    load_reconstruction_spec,
    reconstruct_and_persist_wff_baseline,
    render_architecture_memory_markdown,
)
from .phase1_snapshot import (
    Phase1SnapshotError,
    VerifiedPhase1Snapshot,
    verify_phase1_snapshot,
)
from .project_assets import (
    ProjectAssetError,
    VerifiedProjectAsset,
    hydrate_project_asset,
    load_verified_project_catalog,
    promote_project_asset,
    verify_project_asset,
)
from .project_assets_v2 import (
    VerifiedProjectAssetV2,
    verify_project_asset_any,
    verify_project_asset_v2,
)
from .observation_boundary import (
    ACTIVE_SCANNER_PATH_PREFIXES,
    ORACLE_PATH_PREFIXES,
    PHASE_ID,
    PROTECTED_PATH_PREFIXES,
    RUNTIME_STATE_PATH_PREFIXES,
    SCHEMA_VERSION,
    VALID_VERDICT,
    evaluate_observation_boundary,
    manifest_json,
    rejected_manifest_copy,
    validate_persisted_observation_manifest,
    write_manifest,
)

__all__ = [
    "AdaptiveExplorationError",
    "CompetencyQuestion",
    "MissionBudget",
    "CoreBoundaryError",
    "CoreExtractionError",
    "CoreMigrationError",
    "MinimalCoreContractError",
    "CapabilityCheckRequest",
    "ExistingCapabilityError",
    "CapabilityQueryError",
    "CapabilityQueryService",
    "FlowQueryError",
    "FlowQueryService",
    "EvolutionIntelligenceError",
    "ChangeImpactRequest",
    "ChangeRegistration",
    "Phase1SnapshotError",
    "VerifiedPhase1Snapshot",
    "ProjectAssetError",
    "VerifiedProjectAsset",
    "VerifiedProjectAssetV2",
    "AdmittedEvidenceError",
    "AdmittedGitReader",
    "BlobReceipt",
    "EVIDENCE_SCHEMA_VERSION",
    "MEMORY_SCHEMA_VERSION",
    "PROFILE_ID",
    "REPORT_SCHEMA_VERSION",
    "KnowledgeReconstructionError",
    "ACTIVE_SCANNER_PATH_PREFIXES",
    "ORACLE_PATH_PREFIXES",
    "PHASE_ID",
    "PROTECTED_PATH_PREFIXES",
    "RUNTIME_STATE_PATH_PREFIXES",
    "SCHEMA_VERSION",
    "VALID_VERDICT",
    "assess_knowledge_sufficiency",
    "build_candidate_knowledge_delta",
    "build_mission_context",
    "build_mission_exploration_plan",
    "collect_git_path_evidence",
    "evaluate_candidate_authority_route",
    "initialize_wae_trace",
    "record_wae_iteration",
    "build_request",
    "evaluate_capability_before_generate",
    "explain_authority",
    "find_capability",
    "get_evidence",
    "get_realizations",
    "trace_flow",
    "build_change_impact_request",
    "build_change_registration",
    "build_wff_architecture_memory",
    "evaluate_observation_boundary",
    "load_fixed_observation_manifest",
    "load_reconstruction_spec",
    "manifest_json",
    "reconstruct_and_persist_wff_baseline",
    "render_architecture_memory_markdown",
    "rejected_manifest_copy",
    "run_existing_capability_check",
    "run_core_boundary_reconstruction",
    "run_core_extraction_audit",
    "run_core_migration_audit",
    "run_minimal_core_contract",
    "register_change",
    "run_phase3_evolution_analysis",
    "transition_change_registration",
    "deferred_verification_needed",
    "validate_persisted_observation_manifest",
    "verify_phase1_snapshot",
    "promote_project_asset",
    "verify_project_asset",
    "verify_project_asset_v2",
    "verify_project_asset_any",
    "hydrate_project_asset",
    "load_verified_project_catalog",
    "write_manifest",
]
